name: aplicacion1_ejemplo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/icons/controller_game_icon.svg
     - assets/icons/victory_icon.svg
     - assets/icons/game_over_icon.svg
     - assets/icons/restart_icon.svg

  fonts:
    - family: Celtica
      fonts:
        - asset: fonts/Celtica-Bold.ttf
        - asset: fonts/Celtica-BoldOblique.ttf
        - asset: fonts/Celtica-Book.ttf
        - asset: fonts/Celtica-BookOblique.ttf
          style: normal

    - family: Caramel
      fonts:
        - asset: fonts/Super-Caramel.ttf
          style: normal

